name: OSV Scanner

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: "40 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  pull-requests: read

jobs:
  pr-scan:
    name: Scan New PR Vulnerabilities
    if: github.event_name == 'pull_request'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@a345acffa64b0eaede81a3d9aae6141214d9c8fc
    permissions:
      contents: read
      security-events: write
      actions: read
      pull-requests: read
    with:
      scan-args: |-
        --recursive
        .

  full-scan:
    name: Scan Dependencies
    if: github.event_name != 'pull_request'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@a345acffa64b0eaede81a3d9aae6141214d9c8fc
    permissions:
      contents: read
      security-events: write
      actions: read
    with:
      scan-args: |-
        --recursive
        .
